services:
  klipper-moonraker:
    # you'll probably want to comment the "image:" line and build your own container, unless you know what you're doing (see https://hub.docker.com/r/melarok/klipp-moon)
    image: melarok/klipp-moon:latest
    container_name: klipper-moonraker
    build:
      dockerfile: main.Dockerfile
      context: "build"
      network: host
    device_cgroup_rules:
      - 'c 166:* rmw'
    cap_add:
      - SYS_NICE
    ports:
      #- <ip_of_your_raspi_here>:7125:7125
      - 192.168.0.4:7125:7125
    volumes:
      - ./data:/home/klippy/printer_data
    devices:
      #- /dev/serial/by-id/<your_printers_id_here>:/dev/printer
      - /dev/serial/by-id/usb-Klipper_lpc1768_1C400119018139AFC072075CC12000F5-if00:/dev/printer
    restart: unless-stopped


  fluidd:
    image: cadriel/fluidd:latest
    container_name: fluidd
    hostname: fluidd
    depends_on:
      - klipper-moonraker
    environment:
      #TZ: "<your_timezone_here>"
      TZ: "Europe/Berlin"
    #ports:
    # - 8080:80
    networks:
      - traefik
    labels:
      #- "traefik.http.routers.fluidd.entrypoints=<your_http_entrypoint_here>"
      #- "traefik.http.routers.fluidd.rule=Host(`<your_subdomain.domain.tld_here>`)"
      - "traefik.enable=true"
      - "traefik.http.routers.fluidd.entrypoints=web"
      - "traefik.http.routers.fluidd.rule=Host(`print.pi`)"
    restart: unless-stopped

networks:
  traefik:
    external: true
